# Generated by Django 4.0 on 2021-12-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transportitem',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='maincategory',
            old_name='name',
            new_name='child_name',
        ),
    ]
