# Generated by Django 4.0 on 2021-12-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_app', '0002_alter_color_options_alter_maincategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='parent',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
