# Generated by Django 4.0 on 2021-12-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_app', '0004_remove_maincategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='parent_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
