# Generated by Django 4.0 on 2021-12-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_app', '0006_alter_maincategory_parent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='child_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='parent_name',
        ),
    ]
